[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.7",
    "openai>=2.6.1",
    "pillow>=12.0.0",
    "psutil>=7.1.2",
    "watchdog>=6.0.0",
]
